In [1]:
import sys
assert sys.version_info >= (3, 5)

In [2]:
import sys
assert sys.version_info >= (3, 5)

In [3]:
try:
    # %tensorflow_version only exists in Colab.
    %tensorflow_version 2.x
    IS_COLAB = True
except Exception:
    IS_COLAB = False

In [4]:
import numpy as np
import pandas as pd
import os

In [5]:
import tensorflow as tf
from tensorflow import keras
assert tf.__version__ >= "2.0"

In [6]:
excel_file = 'train.xlsx'
data = pd.read_excel(excel_file)
(data.head())

date    close
0 2018-11-13  1631.17
1 2018-11-12  1636.85
2 2018-11-09  1712.43
3 2018-11-08  1754.91
4 2018-11-07  1755.49

In [7]:
data = data.sort_values(by='date')
(data.head())

date     close
1499 2012-11-30  252.0500
1498 2012-12-03  250.3291
1497 2012-12-04  252.4881
1496 2012-12-05  253.9600
1495 2012-12-06  253.3700

In [8]:
data.drop(['date'], axis=1)

close
1499   252.0500
1498   250.3291
1497   252.4881
1496   253.9600
1495   253.3700
...         ...
4     1755.4900
3     1754.9100
2     1712.4300
1     1636.8500
0     1631.1700

[1500 rows x 1 columns]

In [9]:
training_set = data.iloc[:,1:2].values

In [10]:
training_set


array([[ 252.05  ],
       [ 250.3291],
       [ 252.4881],
       ...,
       [1712.43  ],
       [1636.85  ],
       [1631.17  ]])

In [11]:
from sklearn.preprocessing import MinMaxScaler 
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(training_set)

In [12]:
(scaled_data)

array([[0.00382873],
       [0.00286965],
       [0.00407289],
       ...,
       [0.81771469],
       [0.77559312],
       [0.77242759]])

In [13]:
X_train = []
y_train = []
for i in range(40, 1500):
    X_train.append(scaled_data[i-40:i, 0])
    y_train.append(scaled_data[i, 0])
X_train, y_train = np.array(X_train), np.array(y_train)

In [14]:
X_train.shape

(1460, 40)

In [15]:
y_train.shape

(1460,)

In [16]:
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))

In [17]:
X_train.shape

(1460, 40, 1)

In [18]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

Using TensorFlow backend.


In [19]:
model = Sequential()

In [20]:
model.add(LSTM(units=50, return_sequences= True, input_shape=(X_train.shape[1],1)))
model.add(Dropout(0.2))
model.add(LSTM(units=50, return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(units=50, return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(units = 50))
model.add(Dropout(0.2))
model.add(Dense(units=1))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 40, 50)            10400     
_________________________________________________________________
dropout_1 (Dropout)          (None, 40, 50)            0         
_________________________________________________________________
lstm_2 (LSTM)                (None, 40, 50)            20200     
_________________________________________________________________
dropout_2 (Dropout)          (None, 40, 50)            0         
_________________________________________________________________
lstm_3 (LSTM)                (None, 40, 50)            20200     
_________________________________________________________________
dropout_3 (Dropout)          (None, 40, 50)            0         
_________________________________________________________________
lstm_4 (LSTM)                (None, 50)               

In [21]:
model.compile(optimizer='adam', loss='mean_squared_error')

In [22]:
model.fit(X_train, y_train, epochs=30, batch_size=50)

Epoch 1/30
1460/1460 [==============================] - 5s 4ms/step - loss: 0.0174
Epoch 2/30
1460/1460 [==============================] - 3s 2ms/step - loss: 0.0025
Epoch 3/30
1460/1460 [==============================] - 3s 2ms/step - loss: 0.0022
Epoch 4/30
1460/1460 [==============================] - 3s 2ms/step - loss: 0.0022
Epoch 5/30
1460/1460 [==============================] - 3s 2ms/step - loss: 0.0020
Epoch 6/30
1460/1460 [==============================] - 4s 2ms/step - loss: 0.0023
Epoch 7/30
1460/1460 [==============================] - 3s 2ms/step - loss: 0.0019
Epoch 8/30
1460/1460 [==============================] - 3s 2ms/step - loss: 0.0018
Epoch 9/30
1460/1460 [==============================] - 3s 2ms/step - loss: 0.0019
Epoch 10/30
1460/1460 [==============================] - 3s 2ms/step - loss: 0.0018
Epoch 11/30
1460/1460 [==============================] - 3s 2ms/step - loss: 0.0021
Epoch 12/30
1460/1460 [==============================] - 3s 2ms/step - loss: 0.0020
E

In [45]:
model.evaluate(X_train, y_train)

1460/1460 [==============================] - 1s 1ms/step


0.0005792052905260241

In [46]:
excel_file1 = 'test.xlsx'
test_data = pd.read_excel(excel_file1)
(test_data.head())

date    close
0 2019-11-12  1780.10
1 2019-11-11  1771.65
2 2019-11-08  1785.88
3 2019-11-07  1788.20
4 2019-11-06  1795.77

In [47]:
data1 = test_data.sort_values(by='date')
(data1.head())

date    close
249 2018-11-14  1599.01
248 2018-11-15  1619.44
247 2018-11-16  1593.41
246 2018-11-19  1512.29
245 2018-11-20  1495.46

In [48]:
data1 = data1.drop('date',axis = 1)

In [49]:
(data1.head())

close
249  1599.01
248  1619.44
247  1593.41
246  1512.29
245  1495.46

In [50]:
test_set = data1.iloc[:,0:1].values

In [51]:
test_set

array([[1599.01],
       [1619.44],
       [1593.41],
       [1512.29],
       [1495.46],
       [1516.73],
       [1502.06],
       [1581.33],
       [1581.42],
       [1677.75],
       [1673.57],
       [1690.17],
       [1772.36],
       [1668.4 ],
       [1699.19],
       [1629.13],
       [1641.03],
       [1643.24],
       [1663.54],
       [1658.38],
       [1591.91],
       [1520.91],
       [1551.48],
       [1495.08],
       [1460.83],
       [1377.45],
       [1343.96],
       [1470.9 ],
       [1461.64],
       [1478.02],
       [1501.97],
       [1539.13],
       [1500.28],
       [1575.39],
       [1629.51],
       [1656.58],
       [1659.42],
       [1656.22],
       [1640.56],
       [1617.21],
       [1674.56],
       [1683.78],
       [1693.22],
       [1696.2 ],
       [1632.17],
       [1640.02],
       [1654.93],
       [1670.57],
       [1637.89],
       [1593.88],
       [1670.43],
       [1718.73],
       [1626.23],
       [1633.31],
       [1658.81],
       [16

In [52]:
test_scaled_data = scaler.fit_transform(test_set)

In [53]:
len(test_scaled_data)

250

In [54]:
X_test = []
y_test = []
for i in range(40, 250):
    X_test.append(test_scaled_data[i-40:i, 0])
    y_test.append(test_scaled_data[i, 0])
X_test, y_test = np.array(X_test), np.array(y_test)

In [55]:
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))

In [56]:
X_test.shape

(210, 40, 1)

In [57]:
model.evaluate(X_test,y_test)

210/210 [==============================] - 0s 613us/step


0.01067052916180165